### ISSUE TITLE
Lesson 5 uses `checkPoint` instead of `isSolid`

### ISSUE THREAD

**Issue by FFX01** [def-/nim-platformer#1]
Lesson 5 in the tutorial [here](https://hookrace.net/blog/writing-a-2d-platform-game-in-nim-with-sdl2/) uses the `checkPoint` routine instead of the correct `isSolid` routine for the `onGround` and `testBox` routine declarations. As far as I can tell, this is not addressed in the blog post. The program will not compile with this code as the `checkPoint` routine does not exist.

**Comment by def-** [comment]
Thanks, fixed.

**Comment by FFX01** [comment]
Thanks for getting to this so quickly!
